Repository aliatayee/catalog-of-my-things, pull requests merged in 2022-09, with the labels that each got.

#33 Group Tasks
  .github/workflows/linters.yml
  .github/workflows/tests.yml
  .rubocop.yml
  main.rb
  models/item.rb
  modules/app.rb
  modules/options.rb
Labels: enhancement

#35 Fix Logic Error
  models/item.rb
  modules/app.rb
  modules/options.rb
Labels: bug

#37 Album And Genre Classes
  models/genre.rb
  models/music_album.rb
Labels: enhancement

#39 List Movie And Preserve Data In JSON
  controllers/movie.rb
  data/movies.json
  main.rb
  models/item.rb
  models/movie.rb
  models/source.rb
  modules/app.rb
  modules/file_handle.rb
  modules/options.rb
  modules/static_data.rb
  modules/utility.rb
Labels: enhancement

#44 SQL Schema
  schema/schema.sql
Labels: enhancement

#46 Preserve label & book
  controllers/book.rb
  controllers/label.rb
  data/books.json
  data/labels.json
  data/movies.json
  main.rb
  models/book.rb
  models/item.rb
  models/label.rb
  modules/app.rb
  modules/date_handle.rb
Labels: enhancement

#49 Add unit test for label & book class
  spec/book_spec.rb
  spec/label_spec.rb
Labels: enhancement

#50 Add book table schema
  schema/schema.sql
Labels: enhancement

#57 Bug Fixing ( Test #1 )
  controllers/book.rb
  controllers/label.rb
  data/books.json
  data/games.json
  data/labels.json
  data/movies.json
  data/musics.json
  modules/app.rb
  modules/options.rb
  modules/static_data.rb
  modules/utility.rb
Labels: bug

#48 CREATE README And Add video link
  README.md
Labels: documentation
